### ISSUE TITLE
[Bug]: Blob#bytes works in Deno (1.45.2) but not Deploy

### ISSUE THREAD

**Issue by lionel-rowe** [denoland/deploy_feedback#695]
### Problem description

Calling the `bytes` method of a `Blob` or `File` in Deno Deploy throws `TypeError: (intermediate value).bytes is not a function`. Identical code in Deno works as expected. [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Blob/bytes) lists Deno 1.45 support.

### Steps to reproduce

```ts
await new Blob(['a']).bytes()
```

### Expected behavior

```
Uint8Array(1) [ 97 ]
```

### Environment

~~`Deno.version` gives `{ deno: "", v8: "", typescript: "" }` in Deploy 🤷~~

`navigator.userAgent` is `"Deno/1.41.0"`

### Additional context

Repro: https://dash.deno.com/playground/blob-bytes-repro

**Comment by lionel-rowe** [comment]
`navigator.userAgent` is now `Deno/1.46.3` and as a result `Blob#bytes` is now available.
